import {createRequire} from 'node:module';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=wr('miniflare');
const mf=new Miniflare({modules:[{type:'ESModule',path:path.resolve('dist/server/index.js')},...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js').map(f=>({type:'ESModule',path:path.resolve('dist/server',f)}))],modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET']});
let count=0;const user='qa-integration',headers={'oai-authenticated-user-id':user,'oai-authenticated-user-email':'qa@example.test','Content-Type':'application/json'};
async function request(a,userHeaders=headers){const r=await mf.dispatchFetch('http://localhost/api/state',{method:a?'POST':'GET',headers:userHeaders,...(a?{body:JSON.stringify(a)}:{})});return {status:r.status,data:await r.json()};}
async function post(a){const r=await request(a);assert.equal(r.status,200,JSON.stringify(r.data));return r.data.state;}
function ok(){count++;}
try{
 const db=await mf.getD1Database('DB');await db.exec((await readFile('drizzle/0000_slippery_colleen_wing.sql','utf8')).replaceAll('\n',' '));
 assert.equal((await request(null,{})).status,401);ok();
 let s=await post({type:'login'});assert.deepEqual([s.xp,s.coins],[10,5]);s=await post({type:'login'});assert.equal(s.xp,10);ok();
 s=await post({type:'start',id:'session1',plan:['leg','chest'],title:'QA training'});
 assert.equal((await request({type:'finish',sessionId:'session1',duration:600,note:''})).status,400);ok();
 const set={type:'set',sessionId:'session1',id:'s1',exercise:'leg',weight:20,reps:12};await post(set);s=await post(set);assert.equal(s.sessions[0].sets.length,1);ok();
 await Promise.all([0,1,2].map(i=>post({...set,id:'concurrent'+i})));s=(await request()).data.state;assert.equal(s.sessions[0].sets.length,4);ok();
 s=await post({type:'finish',sessionId:'session1',duration:600,note:'保存テスト'});assert.equal(s.xp,75);const xp=s.xp;s=await post({type:'finish',sessionId:'session1',duration:600,note:''});assert.equal(s.xp,xp);ok();
 s=await post({type:'claim',quest:'set'});s=await post({type:'claim',quest:'set'});assert.equal(s.xp,95);assert.equal((await request({type:'claim',quest:'form'})).status,400);ok();
 s=await post({type:'editSet',sessionId:'session1',id:'s1',weight:25,reps:10});assert.equal(s.sessions[0].sets[0].weight,25);ok();
 s=await post({type:'timer',mode:'start',seconds:90});assert.ok(s.timer.endAt);s=await post({type:'timer',mode:'pause',seconds:0});assert.equal(s.timer.endAt,null);assert.ok(s.timer.remaining>0);ok();
 s=await post({type:'review',id:'r1',exercise:'leg',checks:[true,false,true],note:'ゆっくり戻す'});assert.equal(s.reviews.length,1);await post({type:'claim',quest:'form'});ok();
 s=(await request(null,{...headers,'oai-authenticated-user-id':'qa-other'})).data.state;assert.equal(s.sessions.length,0);ok();
 assert.equal((await request({...set,weight:-5})).status,400);assert.equal((await request({type:'login'},{...headers,Origin:'https://invalid.example'})).status,403);ok();
 await post({type:'start',id:'session2',plan:['leg'],title:'取消テスト'});s=await post({type:'deleteSession',sessionId:'session2'});assert.ok(!s.sessions.some(x=>x.id==='session2'));ok();
 const clip=new Uint8Array([0,0,0,24,102,116,121,112,105,115,111,109]);
 const vr=await mf.dispatchFetch('http://localhost/api/video',{method:'POST',headers:{...headers,'Content-Type':'video/mp4','Content-Length':String(clip.length)},body:clip});assert.equal(vr.status,200,await vr.clone().text());const {id}=await vr.json();
 await post({type:'review',id:'r2',exercise:'chest',checks:[true,true,true],note:'video test',videoId:id});
 const replay=await mf.dispatchFetch('http://localhost/api/video?id='+id,{headers});assert.equal(replay.status,200);assert.deepEqual(new Uint8Array(await replay.arrayBuffer()),clip);
 const other=await mf.dispatchFetch('http://localhost/api/video?id='+id,{headers:{...headers,'oai-authenticated-user-id':'qa-other'}});assert.equal(other.status,404);ok();
 const range=await mf.dispatchFetch('http://localhost/api/video?id='+id,{headers:{...headers,Range:'bytes=0-3'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,4);ok();
 const reflection={type:'review',id:'self-review',exercise:'row',checks:[true,false,null],note:'肘を引く位置を確認する',method:'self'};
 s=await post(reflection);const savedReflection=s.reviews.find(x=>x.id==='self-review');assert.deepEqual(savedReflection.checks,[true,false,null]);assert.equal(savedReflection.method,'self');assert.equal(savedReflection.videoId,undefined);ok();
 s=await post(reflection);assert.equal(s.reviews.filter(x=>x.id==='self-review').length,1);assert.deepEqual((await request()).data.state.reviews.find(x=>x.id==='self-review').checks,[true,false,null]);ok();
 assert.equal((await request({...reflection,id:'invalid-self',checks:['ok',false,null]})).status,400);s=(await request()).data.state;assert.deepEqual(s.reviews.find(x=>x.id==='r1').checks,[true,false,true]);ok();
 const beforeSchedule=(await request()).data.state;
 assert.deepEqual(beforeSchedule.trainingDays,[0,2]);s=await post({type:'schedule',days:[4,1,4]});assert.deepEqual(s.trainingDays,[1,4]);assert.deepEqual((await request()).data.state.trainingDays,[1,4]);
 const {trainingDays:oldDays,...beforeData}=beforeSchedule;const {trainingDays:newDays,...afterData}=s;assert.deepEqual(afterData,beforeData);ok();
 s=await post({type:'schedule',days:[]});assert.deepEqual(s.trainingDays,[]);assert.deepEqual((await request()).data.state.trainingDays,[]);ok();
 assert.equal((await request({type:'schedule',days:[7]})).status,400);assert.equal((await request({type:'schedule',days:[1.5]})).status,400);assert.equal((await request({type:'schedule',days:['月']})).status,400);assert.deepEqual((await request()).data.state.trainingDays,[]);ok();
 const legacyState={...beforeSchedule};delete legacyState.trainingDays;
 await db.prepare('INSERT INTO training_state (user_id, data, revision) VALUES (?, ?, 0)').bind('qa-legacy-schedule',JSON.stringify(legacyState)).run();
 const legacyResult=await request(null,{...headers,'oai-authenticated-user-id':'qa-legacy-schedule'});assert.deepEqual(legacyResult.data.state.trainingDays,[0,2]);assert.deepEqual(legacyResult.data.state.sessions,legacyState.sessions);ok();
 const {makePlan}=await import('../lib/training.ts');assert.equal(makePlan(35,'good','2026-10-06',[1,4]).title,'全身トレーニング A');assert.equal(makePlan(35,'good','2026-10-09',[1,4]).title,'全身トレーニング B');assert.equal(makePlan(35,'good','2026-10-07',[1,4]).title,'全身トレーニング A');assert.equal(makePlan(35,'good','2026-10-07',[]).title,'全身トレーニング A');ok();
 const beforeFocus=(await request()).data.state;assert.deepEqual(beforeFocus.targetAreas,[]);
 s=await post({type:'focus',areas:['core','chest','core']});assert.deepEqual(s.targetAreas,['chest','core']);assert.deepEqual((await request()).data.state.targetAreas,['chest','core']);
 const {targetAreas:oldFocus,...beforeFocusData}=beforeFocus;const {targetAreas:newFocus,...afterFocusData}=s;assert.deepEqual(afterFocusData,beforeFocusData);ok();
 assert.equal((await request({type:'focus',areas:['unknown']})).status,400);assert.equal((await request({type:'focus',areas:[1]})).status,400);assert.equal((await request({type:'focus',areas:Array(7).fill('chest')})).status,400);assert.deepEqual((await request()).data.state.targetAreas,['chest','core']);ok();
 assert.deepEqual((await request(null,{...headers,'oai-authenticated-user-id':'qa-other'})).data.state.targetAreas,[]);
 s=await post({type:'focus',areas:[]});assert.deepEqual((await request()).data.state.targetAreas,[]);ok();
 const preFocusState={...beforeFocus};delete preFocusState.targetAreas;
 await db.prepare('INSERT INTO training_state (user_id, data, revision) VALUES (?, ?, 0)').bind('qa-legacy-focus',JSON.stringify(preFocusState)).run();
 const focusLegacy=(await request(null,{...headers,'oai-authenticated-user-id':'qa-legacy-focus'})).data.state;assert.deepEqual(focusLegacy.targetAreas,[]);assert.deepEqual(focusLegacy.sessions,preFocusState.sessions);ok();
 assert.deepEqual(makePlan(35,'good','2026-10-05').ids,['leg','chest','lat','curl']);assert.deepEqual(makePlan(35,'good','2026-10-07',[0,2],[]).ids,['leg','chest','row','curl']);assert.deepEqual(makePlan(20,'good','2026-10-05').ids,['leg','chest','lat']);assert.equal(makePlan(50,'good','2026-10-05').sets,2);assert.deepEqual(makePlan(50,'tired','2026-10-05').ids,['leg','chest','lat']);ok();
 for(const [area,exercise] of Object.entries({chest:'chest',back:'lat',legs:'leg',shoulders:'shoulder',arms:'biceps',core:'abs'})){
  const focused=makePlan(20,'good','2026-10-05',[0,2],[area]);assert.deepEqual(focused.ids,[exercise]);assert.equal(focused.sets,1);
 }
 assert.deepEqual(makePlan(20,'good','2026-10-07',[0,2],['back']).ids,['row']);assert.deepEqual(makePlan(35,'good','2026-10-05',[0,2],['chest','back']).ids,['chest','lat','row']);ok();
 const areas=['chest','back','legs','shoulders','arms','core'],allAreasPlan=makePlan(20,'good','2026-10-05',[0,2],areas);assert.deepEqual(allAreasPlan.ids,['chest','lat','leg','shoulder','biceps','abs']);assert.ok(allAreasPlan.minutes>20);
 const tiredPlan=makePlan(50,'tired','2026-10-05',[0,2],areas);assert.equal(tiredPlan.sets,1);assert.equal(tiredPlan.ids.length,6);assert.equal(makePlan(35,'pain','2026-10-05',[0,2],areas).ids.length,0);ok();
 await post({type:'focus',areas:['shoulders','arms','core']});s=await post({type:'start',id:'focus-session',plan:['shoulder','biceps','abs'],title:'肩・腕・お腹のメニュー',targetAreas:['shoulders','arms','core'],minutes:35});
 for(const exercise of ['shoulder','biceps','abs'])await post({type:'set',sessionId:'focus-session',id:'focus-set-'+exercise,exercise,weight:5,reps:12});
 const activeFocusSession=(await request()).data.state.sessions.find(session=>session.id==='focus-session');
 s=await post({type:'focus',areas:['legs']});assert.deepEqual(s.sessions.find(session=>session.id==='focus-session'),activeFocusSession);assert.deepEqual(s.sessions.find(session=>session.id==='focus-session').targetAreas,['shoulders','arms','core']);ok();
 for(const exercise of ['shoulder','biceps','abs'])await post({type:'review',id:'focus-review-'+exercise,exercise,checks:[true,null,false],note:'軽い重さで確認',method:'self'});
 s=(await request()).data.state;assert.equal(s.reviews.filter(review=>review.id.startsWith('focus-review-')).length,3);await post({type:'finish',sessionId:'focus-session',duration:600,note:'部位メニューの記録'});assert.ok((await request()).data.state.sessions.find(session=>session.id==='focus-session').finishedAt);ok();
 const {jstDate,dayOffset,measurementSeries,measurementSummary,signedChange}=await import('../lib/training.ts');
 const today=jstDate(),weekAgo=dayOffset(today,-7),monthEdge=dayOffset(today,-29),outsideMonth=dayOffset(today,-30);
 const beforeBody=(await request()).data.state;assert.deepEqual(beforeBody.measurements,[]);
 const bodyEntry={type:'measurement',date:today,weight:105.3,bodyFat:null,note:'朝、起床後に測定'};
 s=await post(bodyEntry);assert.deepEqual(s.measurements,[{date:today,weight:105.3,bodyFat:null,note:bodyEntry.note}]);
 const {measurements:oldMeasurements,...beforeBodyData}=beforeBody;const {measurements:newMeasurements,...afterBodyData}=s;assert.deepEqual(afterBodyData,beforeBodyData);assert.deepEqual((await request()).data.state.measurements,s.measurements);ok();
 await post(bodyEntry);s=await post({...bodyEntry,weight:104.8,bodyFat:29.1,note:'再測定'});assert.equal(s.measurements.length,1);assert.equal(s.measurements[0].weight,104.8);assert.equal(s.measurements[0].bodyFat,29.1);
 s=await post({...bodyEntry,weight:104.8,bodyFat:null});assert.equal(s.measurements[0].bodyFat,null);ok();
 await Promise.all([{date:weekAgo,weight:105.8,bodyFat:31.2},{date:outsideMonth,weight:106.7,bodyFat:null},{date:monthEdge,weight:106.4,bodyFat:31.5}].map(values=>post({...bodyEntry,...values,note:''})));
 s=(await request()).data.state;assert.deepEqual(s.measurements.map(record=>record.date),[outsideMonth,monthEdge,weekAgo,today]);
 const bodySummary=measurementSummary([...s.measurements].reverse());assert.equal(bodySummary.latest.date,today);assert.equal(bodySummary.latestFat.date,weekAgo);assert.equal(signedChange(bodySummary.previousChange),'-1.0');assert.equal(signedChange(bodySummary.totalChange),'-1.9');assert.equal(signedChange(0),'0.0');assert.equal(signedChange(0.1),'+0.1');ok();
 const bodySeries=measurementSeries(s.measurements,'30',today,'weight');assert.deepEqual(bodySeries.map(record=>record.date),[monthEdge,weekAgo,today]);assert.equal(bodySeries[2].timestamp-bodySeries[1].timestamp,7*86400000);
 assert.deepEqual(measurementSeries(s.measurements,'30',today,'bodyFat').map(record=>record.value),[31.5,31.2]);assert.equal(measurementSeries(s.measurements,'90',today,'weight').length,4);assert.equal(measurementSeries(s.measurements,'all',today,'weight').length,4);assert.equal(measurementSummary([bodyEntry]).previousChange,null);assert.deepEqual(measurementSeries([],'all',today,'weight'),[]);ok();
 const bodyBeforeInvalid=s.measurements;
 for(const patch of [{date:dayOffset(today,1)},{date:'2026-02-30'},{date:'not-a-date'},{weight:0},{weight:501},{weight:105.35},{weight:'105'},{bodyFat:100},{bodyFat:-1},{note:'x'.repeat(501)}])assert.equal((await request({...bodyEntry,...patch})).status,400,JSON.stringify(patch));
 assert.deepEqual((await request()).data.state.measurements,bodyBeforeInvalid);ok();
 assert.equal((await request({...bodyEntry,originalDate:weekAgo})).status,400);assert.deepEqual((await request()).data.state.measurements,bodyBeforeInvalid);
 const correctedDate=dayOffset(today,-1);s=await post({...bodyEntry,date:correctedDate,originalDate:weekAgo,weight:105.8,bodyFat:31.2});assert.equal(s.measurements.length,4);assert.ok(!s.measurements.some(record=>record.date===weekAgo));assert.equal(s.measurements.find(record=>record.date===correctedDate).weight,105.8);ok();
 s=await post({type:'deleteMeasurement',date:outsideMonth});s=await post({type:'deleteMeasurement',date:outsideMonth});assert.equal(s.measurements.length,3);assert.equal(s.measurements.at(-1).date,today);assert.equal((await request({...bodyEntry,originalDate:outsideMonth})).status,400);ok();
 assert.deepEqual((await request(null,{...headers,'oai-authenticated-user-id':'qa-other'})).data.state.measurements,[]);
 const legacyBody={...beforeBody};delete legacyBody.measurements;await db.prepare('INSERT INTO training_state (user_id, data, revision) VALUES (?, ?, 0)').bind('qa-legacy-body',JSON.stringify(legacyBody)).run();
 const restoredBody=(await request(null,{...headers,'oai-authenticated-user-id':'qa-legacy-body'})).data.state;assert.deepEqual(restoredBody.measurements,[]);assert.deepEqual(restoredBody.sessions,legacyBody.sessions);ok();
 const html=await mf.dispatchFetch('http://localhost/');const text=await html.text();assert.equal(html.status,200);assert.ok(text.includes('今日も、自分のペースで。'));assert.ok(text.includes('からだの記録'));assert.ok(text.includes('体重を記録'));assert.ok(!text.includes('Starter Project'));ok();
 console.log(`PASS ${count} integration scenarios: authentication, durable records, duplicates, concurrent updates, rewards, editing, timer, form reviews, validation, CSRF, cancellation, legacy private video playback, self-review, weekday schedule persistence and validation, legacy defaults, schedule-based menus, body-area preferences and validation, focus menus, unchanged full-body recommendations, active-session snapshots, new exercise logging and reviews, body measurement CRUD and persistence, date correction and conflicts, concurrent measurements, input validation, period boundaries, null body fat, chronological summaries, user isolation, SSR.`);
}finally{await mf.dispose();}
